export const FETCH_USERS_START = 'FETCH_USER_START';
export const FETCH_USERS_SUCCESS = 'FETCH_USER_SUCCESS';


export const SET_PAYROLL_SEARCH = 'SET_PAYROLL_SEARCH';
export const SET_AS400_SEARCH = 'SET_AS400_SEARCH';
export const SET_AD_SEARCH = 'SET_AD_SEARCH';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const ADD_ADJUSTMENT_INIT = 'ADD_ADJUSTMENT_INIT';
export const ADD_ADJUSTMENT_SUCCESS = 'ADD_ADJUSTMENT_SUCCESS';
export const ADD_ADJUSTMENT_START = 'ADD_ADJUSTMENT_START';
export const ADD_ADJUSTMENT_CANCEL = 'ADD_ADJUSTMENT_CANCEL';

export const EDIT_ADJUSTMENT_COMMENT = 'EDIT_ADJUSTMENT_COMMENT'
export const EDIT_ADJUSTMENT_DATE = 'EDIT_ADJUSTMENT_DATE';
export const EDIT_ADJUSTMENT_AMOUNT = 'EDIT_ADJUSTMENT_AMOUNT';

export const FETCH_ADJUSTMENTS_START = 'FETCH_ADJUSTMENTS_START';
export const FETCH_ADJUSTMENTS_SUCCESS = 'FETCH_ADJUSTMENTS_SUCCESS';
export const SET_CURRENT_USER_ADJUSTMENTS = 'SET_CURRENT_USER_ADJUSTMENTS';


export const ADD_AFTER_FLOOR_ADJUSTMENT_SUCCESS = 'ADD_AFTER_FLOOR_ADJUSTMENT_SUCCESS';
export const ADD_AFTER_FLOOR_ADJUSTMENT_START = 'ADD_AFTER_FLOOR_ADJUSTMENT_START';

export const EDIT_AFTER_FLOOR_ADJUSTMENT_COMMENT = 'EDIT_AFTER_FLOOR_ADJUSTMENT_COMMENT'
export const EDIT_AFTER_FLOOR_ADJUSTMENT_DATE = 'EDIT_AFTER_FLOOR_ADJUSTMENT_DATE';
export const EDIT_AFTER_FLOOR_ADJUSTMENT_AMOUNT = 'EDIT_AFTER_FLOOR_ADJUSTMENT_AMOUNT';

export const FETCH_AFTER_FLOOR_ADJUSTMENTS_START = 'FETCH_AFTER_FLOOR_ADJUSTMENTS_START';
export const FETCH_AFTER_FLOOR_ADJUSTMENTS_SUCCESS = 'FETCH_AFTER_FLOOR_ADJUSTMENTS_SUCCESS';
export const SET_CURRENT_USER_AFTER_FLOOR_ADJUSTMENTS = 'SET_CURRENT_USER_AFTER_FLOOR_ADJUSTMENTS';


export const SET_OPODefault = "SET_OPODefault";
