export const FETCH_USERS_START = 'FETCH_USER_START';
export const FETCH_USERS_SUCCESS = 'FETCH_USER_SUCCESS';


export const SET_PAYROLL_SEARCH = 'SET_PAYROLL_SEARCH';
export const SET_AS400_SEARCH = 'SET_AS400_SEARCH';
export const SET_AD_SEARCH = 'SET_AD_SEARCH';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const ADD_ADJUSTMENT_SUCCESS = 'ADD_ADJUSTMENT_SUCCESS';
export const ADD_ADJUSTMENT_START = 'ADD_ADJUSTMENT_START';

export const SELECT_ADJUSTMENT = 'SELECT_ADJUSTMENT';

export const DELETE_ADJUSTMENT_START = 'DELETE_ADJUSTMENT_START';
export const DELETE_ADJUSTMENT_SUCCESS = 'DELETE_ADJUSTMENT_SUCCESS';

export const EDIT_ADJUSTMENT_COMMENT = 'EDIT_ADJUSTMENT_COMMENT';
export const EDIT_ADJUSTMENT_DATE = 'EDIT_ADJUSTMENT_DATE';
export const EDIT_ADJUSTMENT_AMOUNT = 'EDIT_ADJUSTMENT_AMOUNT';

export const FETCH_ADJUSTMENTS_START = 'FETCH_ADJUSTMENTS_START';
export const FETCH_ADJUSTMENTS_SUCCESS = 'FETCH_ADJUSTMENTS_SUCCESS';
export const SET_CURRENT_USER_ADJUSTMENTS = 'SET_CURRENT_USER_ADJUSTMENTS';


export const ADD_AFTER_FLOOR_ADJUSTMENT_SUCCESS = 'ADD_AFTER_FLOOR_ADJUSTMENT_SUCCESS';
export const ADD_AFTER_FLOOR_ADJUSTMENT_START = 'ADD_AFTER_FLOOR_ADJUSTMENT_START';

export const EDIT_AFTER_FLOOR_ADJUSTMENT_COMMENT = 'EDIT_AFTER_FLOOR_ADJUSTMENT_COMMENT';
export const EDIT_AFTER_FLOOR_ADJUSTMENT_DATE = 'EDIT_AFTER_FLOOR_ADJUSTMENT_DATE';
export const EDIT_AFTER_FLOOR_ADJUSTMENT_AMOUNT = 'EDIT_AFTER_FLOOR_ADJUSTMENT_AMOUNT';

export const FETCH_AFTER_FLOOR_ADJUSTMENTS_START = 'FETCH_AFTER_FLOOR_ADJUSTMENTS_START';
export const FETCH_AFTER_FLOOR_ADJUSTMENTS_SUCCESS = 'FETCH_AFTER_FLOOR_ADJUSTMENTS_SUCCESS';
export const SET_CURRENT_USER_AFTER_FLOOR_ADJUSTMENTS = 'SET_CURRENT_USER_AFTER_FLOOR_ADJUSTMENTS';


export const EDIT_OPCODEFAULT_GROUP_NAME = "EDIT_OPCODEFAULT_GROUP_NAME";
export const EDIT_OPCODEFAULT_COMMISSION_MODEL = 'EDIT_OPCODEFAULT_COMMISSION_MODEL';
export const EDIT_OPCODEFAULT_FLOOR = 'EDIT_OPCODEFAULT_FLOOR';
export const EDIT_OPCODEFAULT_SEASONAL_FLOOR = 'EDIT_OPCODEFAULT_SEASONAL_FLOOR';
export const EDIT_OPCODEFAULT_GUARANTEE_PERCENTAGE = 'EDIT_OPCODEFAULT_GUARANTEE_PERCENTAGE';
export const EDIT_OPCODEFAULT_BONUS_MODELS = 'EDIT_OPCODEFAULT_BONUS_MODELS';
export const EDIT_OPCODEFAULT_ORG_LEVEL = 'EDIT_OPCODEFAULT_ORG_LEVEL';
export const EDIT_OPCODEFAULT_LOCATION = 'EDIT_OPCODEFAULT_LOCATION';
export const EDIT_OPCODEFAULT_EMAIL = 'EDIT_OPCODEFAULT_EMAIL';
export const TOGGLE_OPCODEFAULT_GUARANTEE_BONUS = 'TOGGLE_OPCODEFAULT_GUARANTEE_BONUS';
export const TOGGLE_OPCODEFAULT_LOW = 'TOGGLE_OPCODEFAULT_LOW';
export const TOGGLE_OPCODEFAULT_MEDIUM = 'TOGGLE_OPCODEFAULT_MEDIUM';
export const TOGGLE_OPCODEFAULT_HIGH = 'TOGGLE_OPCODEFAULT_HIGH';
export const TOGGLE_OPCODEFAULT_FLIGHT_A = 'TOGGLE_OPCODEFAULT_FLIGHT_A';
export const TOGGLE_OPCODEFAULT_FLIGHT_B = 'TOGGLE_OPCODEFAULT_FLIGHT_B';
export const TOGGLE_OPCODEFAULT_FLIGHT_C= 'TOGGLE_OPCODEFAULT_FLIGHT_C';
export const TOGGLE_OPCODEFAULT_FLIGHT_D = 'TOGGLE_OPCODEFAULT_FLIGHT_D';
export const TOGGLE_OPCODEFAULT_FLIGHT_E = 'TOGGLE_OPCODEFAULT_FLIGHT_E';
export const TOGGLE_OPCODEFAULT_TRS = 'TOGGLE_OPCODEFAULT_TRS';
export const TOGGLE_OPCODEFAULT_TRP = 'TOGGLE_OPCODEFAULT_TRP';
export const TOGGLE_OPCODEFAULT_LLC = 'TOGGLE_OPCODEFAULT_LLC';
export const TOGGLE_OPCODEFAULT_CMU = 'TOGGLE_OPCODEFAULT_CMU';
export const TOGGLE_OPCODEFAULT_OTH = 'TOGGLE_OPCODEFAULT_OTH';


export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION';
export const REMOVE_ALL_NOTIFICATIONS = 'REMOVE_ALL_NOTIFICATIONS';

